# Generated by Django 4.0.2 on 2022-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('age', models.IntegerField(max_length=3, verbose_name='Age')),
                ('profession', models.TextField(verbose_name='Profession')),
            ],
        ),
    ]
